In [1]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import nltk

In [3]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [4]:
import pandas as pd
import numpy as np

In [27]:
data=pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\assignments\\ML\\nlp\\nlp_dataset.csv")

In [28]:
data

Comment Emotion
0     i seriously hate one subject to death but now ...    fear
1                    im so full of life i feel appalled   anger
2     i sit here to write i start to dig out my feel...    fear
3     ive been really angry with r and i feel like a...     joy
4     i feel suspicious if there is no one outside l...    fear
...                                                 ...     ...
5932                 i begun to feel distressed for you    fear
5933  i left feeling annoyed and angry thinking that...   anger
5934  i were to ever get married i d have everything...     joy
5935  i feel reluctant in applying there because i w...    fear
5936  i just wanted to apologize to you because i fe...   anger

[5937 rows x 2 columns]

### Text cleaning

#### step 1: converting to lowercase

In [7]:
row_doc1=[doc.lower() for doc in data['Comment']]
row_doc2=[doc.lower() for doc in data['Emotion']]
print(row_doc1)
print(row_doc2)

['i seriously hate one subject to death but now i feel reluctant to drop it', 'im so full of life i feel appalled', 'i sit here to write i start to dig out my feelings and i think that i am afraid to accept the possibility that he might not make it', 'ive been really angry with r and i feel like an idiot for trusting him in the first place', 'i feel suspicious if there is no one outside like the rapture has happened or something', 'i feel jealous becasue i wanted that kind of love the true connection between two souls and i wanted that', 'when a friend of mine keeps telling me morbid things that happened to his dog', 'i finally fell asleep feeling angry useless and still full of anxiety', 'i feel a bit annoyed and antsy in a good way', 'i feel like i ve regained another vital part of my life which is living', 'i feel a bit like franz liebkind in the producers not many people know it but the fuhrer was a terrific dancer', 'i was feeling at the start didnt want to move much at all was re

#### step 2: tokenization

In [37]:
from nltk import word_tokenize
tokenized_data1=[word_tokenize(doc) for doc in row_doc1]
print(tokenized_data1)
tokenized_data2=[word_tokenize(doc) for doc in row_doc2]
print(tokenized_data2)

[['i', 'seriously', 'hate', 'one', 'subject', 'to', 'death', 'but', 'now', 'i', 'feel', 'reluctant', 'to', 'drop', 'it'], ['im', 'so', 'full', 'of', 'life', 'i', 'feel', 'appalled'], ['i', 'sit', 'here', 'to', 'write', 'i', 'start', 'to', 'dig', 'out', 'my', 'feelings', 'and', 'i', 'think', 'that', 'i', 'am', 'afraid', 'to', 'accept', 'the', 'possibility', 'that', 'he', 'might', 'not', 'make', 'it'], ['ive', 'been', 'really', 'angry', 'with', 'r', 'and', 'i', 'feel', 'like', 'an', 'idiot', 'for', 'trusting', 'him', 'in', 'the', 'first', 'place'], ['i', 'feel', 'suspicious', 'if', 'there', 'is', 'no', 'one', 'outside', 'like', 'the', 'rapture', 'has', 'happened', 'or', 'something'], ['i', 'feel', 'jealous', 'becasue', 'i', 'wanted', 'that', 'kind', 'of', 'love', 'the', 'true', 'connection', 'between', 'two', 'souls', 'and', 'i', 'wanted', 'that'], ['when', 'a', 'friend', 'of', 'mine', 'keeps', 'telling', 'me', 'morbid', 'things', 'that', 'happened', 'to', 'his', 'dog'], ['i', 'finally',

#### step 3: punctuation removal

In [9]:
import string
import re
regex = re.compile('[%s]' % re.escape(string.punctuation))
tokenized_data_no_punctuation1=[]
for review in tokenized_data1:
    new_review=[]
    for token in review:
        new_token = regex.sub(u'', token)
        if not new_token==u'':
            new_review.append(new_token)

    tokenized_data_no_punctuation1.append(new_review)
print(tokenized_data_no_punctuation1)

[['i', 'seriously', 'hate', 'one', 'subject', 'to', 'death', 'but', 'now', 'i', 'feel', 'reluctant', 'to', 'drop', 'it'], ['im', 'so', 'full', 'of', 'life', 'i', 'feel', 'appalled'], ['i', 'sit', 'here', 'to', 'write', 'i', 'start', 'to', 'dig', 'out', 'my', 'feelings', 'and', 'i', 'think', 'that', 'i', 'am', 'afraid', 'to', 'accept', 'the', 'possibility', 'that', 'he', 'might', 'not', 'make', 'it'], ['ive', 'been', 'really', 'angry', 'with', 'r', 'and', 'i', 'feel', 'like', 'an', 'idiot', 'for', 'trusting', 'him', 'in', 'the', 'first', 'place'], ['i', 'feel', 'suspicious', 'if', 'there', 'is', 'no', 'one', 'outside', 'like', 'the', 'rapture', 'has', 'happened', 'or', 'something'], ['i', 'feel', 'jealous', 'becasue', 'i', 'wanted', 'that', 'kind', 'of', 'love', 'the', 'true', 'connection', 'between', 'two', 'souls', 'and', 'i', 'wanted', 'that'], ['when', 'a', 'friend', 'of', 'mine', 'keeps', 'telling', 'me', 'morbid', 'things', 'that', 'happened', 'to', 'his', 'dog'], ['i', 'finally',

#### step 4: Removing stopwords

In [10]:
from nltk.corpus import stopwords
tokenized_data_no_stopwords1=[]
for doc in tokenized_data_no_punctuation1:
    new_term_vector=[]
    for word in doc:
        if not word in stopwords.words('english'):
            new_term_vector.append(word)
    tokenized_data_no_stopwords1.append(new_term_vector)
print(tokenized_data_no_stopwords1)
            
    

[['seriously', 'hate', 'one', 'subject', 'death', 'feel', 'reluctant', 'drop'], ['im', 'full', 'life', 'feel', 'appalled'], ['sit', 'write', 'start', 'dig', 'feelings', 'think', 'afraid', 'accept', 'possibility', 'might', 'make'], ['ive', 'really', 'angry', 'r', 'feel', 'like', 'idiot', 'trusting', 'first', 'place'], ['feel', 'suspicious', 'one', 'outside', 'like', 'rapture', 'happened', 'something'], ['feel', 'jealous', 'becasue', 'wanted', 'kind', 'love', 'true', 'connection', 'two', 'souls', 'wanted'], ['friend', 'mine', 'keeps', 'telling', 'morbid', 'things', 'happened', 'dog'], ['finally', 'fell', 'asleep', 'feeling', 'angry', 'useless', 'still', 'full', 'anxiety'], ['feel', 'bit', 'annoyed', 'antsy', 'good', 'way'], ['feel', 'like', 'regained', 'another', 'vital', 'part', 'life', 'living'], ['feel', 'bit', 'like', 'franz', 'liebkind', 'producers', 'many', 'people', 'know', 'fuhrer', 'terrific', 'dancer'], ['feeling', 'start', 'didnt', 'want', 'move', 'much', 'really', 'glad', 'ex

#### step5:stemming and lemmatisation

In [11]:
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer
porter=PorterStemmer()
wordnet=WordNetLemmatizer()
preprocessed_data1=[]
for data in tokenized_data_no_stopwords1:
    final_data=[]
    for word in data:
        porter.stem(word)
        wordnet.lemmatize(word)
        final_data.append(word)
    preprocessed_data1.append(final_data)
print(preprocessed_data1)
    
    
        


[['seriously', 'hate', 'one', 'subject', 'death', 'feel', 'reluctant', 'drop'], ['im', 'full', 'life', 'feel', 'appalled'], ['sit', 'write', 'start', 'dig', 'feelings', 'think', 'afraid', 'accept', 'possibility', 'might', 'make'], ['ive', 'really', 'angry', 'r', 'feel', 'like', 'idiot', 'trusting', 'first', 'place'], ['feel', 'suspicious', 'one', 'outside', 'like', 'rapture', 'happened', 'something'], ['feel', 'jealous', 'becasue', 'wanted', 'kind', 'love', 'true', 'connection', 'two', 'souls', 'wanted'], ['friend', 'mine', 'keeps', 'telling', 'morbid', 'things', 'happened', 'dog'], ['finally', 'fell', 'asleep', 'feeling', 'angry', 'useless', 'still', 'full', 'anxiety'], ['feel', 'bit', 'annoyed', 'antsy', 'good', 'way'], ['feel', 'like', 'regained', 'another', 'vital', 'part', 'life', 'living'], ['feel', 'bit', 'like', 'franz', 'liebkind', 'producers', 'many', 'people', 'know', 'fuhrer', 'terrific', 'dancer'], ['feeling', 'start', 'didnt', 'want', 'move', 'much', 'really', 'glad', 'ex

### Feature extraction

In [12]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer


#converting processed documents to string
doc_string1=[' '.join(doc) for doc in preprocessed_data1]

print(doc_string1)



['seriously hate one subject death feel reluctant drop', 'im full life feel appalled', 'sit write start dig feelings think afraid accept possibility might make', 'ive really angry r feel like idiot trusting first place', 'feel suspicious one outside like rapture happened something', 'feel jealous becasue wanted kind love true connection two souls wanted', 'friend mine keeps telling morbid things happened dog', 'finally fell asleep feeling angry useless still full anxiety', 'feel bit annoyed antsy good way', 'feel like regained another vital part life living', 'feel bit like franz liebkind producers many people know fuhrer terrific dancer', 'feeling start didnt want move much really glad experience glimpse sort vibrant energy gain year', 'bitten dog', 'always find feeling thankful years gathered tricks allow feel grateful face moments last thing want say thanks', 'try talk anyone feel irritable like', 'feel like hated since', 'dont know wrote following little note feel today u r offende

In [38]:
#using bag of words method
bowvector=CountVectorizer()
bow_matrix1=bowvector.fit_transform(doc_string1)


# vocabulary for refrence
print('\n vocabulary of Bag of words')
print(bowvector.get_feature_names_out())

#Bag of words matrix
print('\n Bag of words matrix:\n')
print('Column:comment\n',bow_matrix1.toarray())




 vocabulary of Bag of words
['aa' 'aac' 'aaron' ... 'zonisamide' 'zq' 'zumba']

 Bag of words matrix:

Column:comment
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
#using tfidf method
tfidfvector=TfidfVectorizer()
tfidf_matrix1=tfidfvector.fit_transform(doc_string1)

#vocabulary
print('\n vocabulary of tfidf')
print(tfidfvector.get_feature_names_out())
#Tf-IDF matrix
print('\n TF-IDF matrix:\n')
print('Column:Comment\n',tfidf_matrix1.toarray())



 vocabulary of tfidf
['aa' 'aac' 'aaron' ... 'zonisamide' 'zq' 'zumba']

 TF-IDF matrix:

Column:Comment
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### 3. Model Development

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

#### SVC(support vector machine)

In [41]:
x=bow_matrix1.toarray()
y=data['Emotion']
np.reshape(y, (1,np.product(y.shape)))
X_train,X_test,Y_train,Y_test=train_test_split(x,y)

In [42]:
from sklearn.svm import SVC
svm_model=SVC()
svm_model.fit(X_train,Y_train)

SVC()

In [44]:
from sklearn.naive_bayes import MultinomialNB
naive_model=MultinomialNB()
naive_model.fit(X_train,Y_train)

MultinomialNB()

In [48]:
from sklearn.metrics import accuracy_score,f1_score

In [52]:
nb_predict=naive_model.predict(X_test)
svm_predict=svm_model.predict(X_test)
nb_accuracy=accuracy_score(Y_test,nb_predict)
svm_accuracy=accuracy_score(Y_test,svm_predict)
nb_f1_score=f1_score(Y_test,nb_predict,average='weighted')
svm_f1_score=f1_score(Y_test,svm_predict,average='weighted')

# Print results
print("Naive Bayes Accuracy:", nb_accuracy)
print("Naive Bayes F1 Score:", nb_f1_score)
print("SVM Accuracy:", svm_accuracy)
print("SVM F1 Score:", svm_f1_score)


Naive Bayes Accuracy: 0.8922558922558923
Naive Bayes F1 Score: 0.8923981877231947
SVM Accuracy: 0.9185185185185185
SVM F1 Score: 0.9184393710285524


### Its clear from the above score that in this case SVM model is more accurate